### ISSUE TITLE
Backwards Constraints

### ISSUE THREAD

**Issue by pachun** [colinta/teacup#56]
I don't know if you did this on purpose or not but I feel like when I say I want something positioned 10pts above another element I'd expect to do it like this:

```
constrain_above(:another_element, 10)
```

as opposed to

```
constrain_above(:another_element, -10)
```

This happens with constrain_right and constrain_above.

I think it was a mistake because you don't have to use negatives either for constrain_to_right or constrain_to_left to have them work the way you'd expect.

I apologize if you meant to do it this way, it just seems a little off to me.

**Comment by pachun** [comment]
constrain_bottom does it too.

**Comment by colinta** [comment]
I agree on `constrain_above` because `above/below` and `to_left/right` imply a direction, so those margins should increase when going in that direction.

`constrain_bottom/right` are _locations_, though, which I think should default to the window's coordinate system.  The system, as it stands, is akin to array indexing with negative numbers, which I really like.

``` ruby
a = [1, 2, 3, 4]
a[0]  # => 1
a[-1]  # => 4
```

So I'm pushing a change that supports this:

``` ruby
constraints: [
  constrain_above(:other, 10),
  constrain_left(10),
  constrain_right(-10),
  constrain_height(30),
]
```

as opposed to

``` ruby
constraints: [
  constrain_above(:other, 10),
  constrain_left(10),
  constrain_right(10),
  constrain_height(30),
]
```

**Comment by pachun** [comment]
Alright sounds good. Thanks!
