### ISSUE TITLE
Style is not applied at Startup

### ISSUE THREAD

**Issue by arkan** [colinta/teacup#84]
Hi,

I'm using teacup to customize my controls including an UINavigationBar.

It works but at startup the style is not applied. If the UINavigationBar hides and shows back, then the style is applied.

I have created a small app which presents my issue. 
Just start the application, and set the focus to the search field and then cancel.

It's probably due to iOS which does some caching on views. 

But I've no idea how to fix it. :-)

https://github.com/Arkan/promotion_with_teacup

Thanks

**Comment by colinta** [comment]
This is probably fixed with an explicit call to `Teacup::Appearance.apply`. I make a note of this in the [Style-via-Appearance section of the README](https://github.com/rubymotion/teacup/#style-via-uiappearance), but I should make that more prominent, since it's pretty much required anytime you want styling applied during startup.

**Comment by arkan** [comment]
Thanks for your reply Colinta.

With a call to Teacup::Appearance.apply it works as expected. 

Thanks
